#!/usr/bin/env bash
# Builds Mod-olcoop.dll with Mono mcs against the game's own managed assemblies.
# GAME_MANAGED: folder with Overload_Data/Managed DLLs (never committed).
# OLMOD_DLL: the installed olmod GameMod.dll (referenced, not shipped).
set -euo pipefail
cd "$(dirname "$0")"
GAME_MANAGED="${GAME_MANAGED:-/mnt/user-data/uploads/Overload/Overload_Data/Managed}"
OLMOD_DLL="${OLMOD_DLL:-/mnt/user-data/uploads/Overload/GameMod.dll}"
OUT=build
mkdir -p "$OUT" src/olcoop/Generated
read VER PHASE < VERSION
IFS=. read MAJ MIN PAT <<< "$VER"
cat > src/olcoop/Generated/Version.g.cs <<EOV
// Generated by build.sh from VERSION. Do not edit.
using System.Reflection;
[assembly: AssemblyTitle("olcoop")]
[assembly: AssemblyVersion("$VER.0")]
[assembly: AssemblyFileVersion("$VER.0")]
[assembly: AssemblyInformationalVersion("$VER-$PHASE")]
namespace OlCoop
{
    public static class CoopVersion
    {
        public const int Major = $MAJ, Minor = $MIN, Patch = $PAT;
        public const string Phase = "$PHASE";
        public const string Built = "$(date -u +%Y-%m-%dT%H:%MZ)";
        public static string Full { get { return "olcoop $VER-$PHASE"; } }
        /// <summary>Wire-protocol version. Host and clients must match exactly.</summary>
        public const int Protocol = 14;
    }
}
EOV
REFS=()
for r in Assembly-CSharp Assembly-CSharp-firstpass System System.Core UnityEngine UnityEngine.CoreModule \
         UnityEngine.Networking UnityEngine.UNETModule UnityEngine.PhysicsModule UnityEngine.IMGUIModule \
         UnityEngine.AudioModule UnityEngine.TextRenderingModule UnityEngine.InputModule UnityEngine.VRModule Newtonsoft.Json; do
  REFS+=("-r:$GAME_MANAGED/$r.dll")
done
mcs -nostdlib -r:"$GAME_MANAGED/mscorlib.dll" "${REFS[@]}" -r:lib/0Harmony.dll -r:"$OLMOD_DLL" \
    -target:library -langversion:7.2 -optimize+ -debug- -warnaserror- -nowarn:618 \
    -out:"$OUT/Mod-olcoop.dll" $(find src/olcoop -name '*.cs' | sort)
echo "Built $OUT/Mod-olcoop.dll"
